apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: deployment-architecture-type-a.k8s.seeq.com
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: k8s.seeq.com/v1alpha1
    kind: XSeeqTenant
  resources:
    - name: seeqinbox
      base:
        apiVersion: k8s.seeq.com/v1alpha1
        kind: XSeeqInBox
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - fromFieldPath: spec.hostname
          toFieldPath: spec.hostname
    - name: datalab
      base:
        apiVersion: k8s.seeq.com/v1alpha1
        kind: XDataLab
      patches:
        - fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - fromFieldPath: spec.hostname
          toFieldPath: spec.hostname
