apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatalabs.k8s.seeq.com
spec:
  group: k8s.seeq.com
  names:
    kind: XDataLab
    plural: xdatalabs
  claimNames:
    kind: DataLab
    plural: datalabs
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              hostname:
                type: string
                pattern: '^[a-zA-Z0-9]+\.[a-zA-Z0-9]+\.[a-zA-Z0-9]+$'
                description: Fully qualified domain name of the tenant. Not all domains are available in all clouds.
            required:
            - hostname
